/**
 * The confident-tiers failure taxonomy.
 *
 * A downstream MCP server's own tool handlers commonly format errors ad hoc,
 * per file, with no shared error-type structure to read off -- and matching
 * that free text would be fragile in a way that misclassifies the moment its
 * wording changes. Confirmed with the
 * user: ship the tiers that are actually reliable, not a guess dressed up as
 * a category.
 *
 * WHAT IS RELIABLE, AND WHY. Read directly from the installed
 * @modelcontextprotocol/sdk (^1.29.0) source, not assumed:
 * `node_modules/@modelcontextprotocol/sdk/dist/esm/server/mcp.js`.
 * McpServer's OWN internal `tools/call` dispatcher wraps tool lookup, input
 * validation and handler execution in ONE try/catch and converts every
 * failure -- including ones from BEFORE any per-tool handler runs -- into a
 * `{content: [{type:'text', text}], isError: true}` result via
 * `createToolError(message)`. It never rethrows to the transport (except the
 * unrelated UrlElicitationRequired case). That means "did the call throw"
 * cannot distinguish anything; the message TEXT has to.
 *
 * The one thing worth relying on: for the two failures that happen INSIDE
 * that dispatcher itself (not inside a tool's own code), the SDK generates
 * the message text itself, verified against this exact version:
 *
 *   unknown/disabled tool   -> "Tool ${name} not found" / "Tool ${name} disabled"
 *   bad arguments           -> "Input validation error: Invalid arguments for tool ${name}: ..."
 *
 * Matching THOSE strings is matching the SDK's own generated text, not the
 * downstream server's -- the same category of bridge the Python SDK's classifier
 * already accepts for the Python MCP SDK (docs/deferred.md's DF-11: "our
 * classifier matches SDK-internal message strings; that is a bridge, not an
 * endpoint"). If a future SDK version changes this wording, classification
 * falls through to `tool_error` rather than crashing -- a safe failure mode,
 * not a silent wrong answer.
 *
 * Everything else that comes back with `isError: true` is the downstream
 * server's own text, and gets exactly one bucket: `tool_error`, undifferentiated. No
 * "AxiosError" / "ECONNREFUSED" pattern-matching -- that was the rejected
 * option, because it degrades the moment wording changes and reports false
 * confidence in the meantime.
 */

export const FailureKind = {
  OK: "ok",
  UNKNOWN_TOOL: "unknown_tool",
  INVALID_ARGUMENTS: "invalid_arguments",
  TOOL_ERROR: "tool_error",
  UNCLASSIFIED: "unclassified",
} as const;

export type FailureKind = (typeof FailureKind)[keyof typeof FailureKind];

/**
 * Where a classification came from -- stamped onto every span so
 * "SDK-verified" is never silently blended with "we just read the isError
 * flag". Mirrors the column the Python schema already has for this
 * (normalizer/normalize.py's `failure_kind_source`).
 */
export const FailureKindSource = {
  CLEAN: "clean",
  SDK_DISPATCH: "sdk-dispatch",
  IS_ERROR_FLAG: "is-error-flag",
  UNCLASSIFIED: "unclassified",
} as const;

export type FailureKindSource = (typeof FailureKindSource)[keyof typeof FailureKindSource];

export interface Classification {
  kind: FailureKind;
  source: FailureKindSource;
}

/**
 * Exact strings generated by McpServer's internal dispatcher
 * (@modelcontextprotocol/sdk ^1.29.0, server/mcp.js) -- version-pinned on
 * purpose, see the module docstring.
 *
 * NOT anchored to the start of the string. Measured against a real
 * connected client/server (tests/dispatch.test.ts): the text these two
 * throws produce arrives prefixed with `MCP error -32602: ` by the time a
 * caller sees it (`ErrorCode.InvalidParams` reformatted somewhere in the
 * SDK's own request/response plumbing, upstream of where this SDK's own
 * dispatch wrapper catches the exception) -- reading the source predicted
 * the UNPREFIXED text; only running it against a real client caught the
 * prefix. Matching a substring rather than the start of the string is
 * correct either way, regardless of which layer adds it.
 */
const UNKNOWN_TOOL_PATTERNS = [/Tool .+ not found/, /Tool .+ disabled/];
const INVALID_ARGUMENTS_PATTERN = /Input validation error: Invalid arguments for tool/;

/**
 * Classifies the first text block of a CallToolResult (or PromptResult).
 * Mirrors the Python classifier's `classify(text: str) -> str` signature
 * closely: takes a plain string, not a span or exception -- a downstream
 * server's own results already arrive as `{content:[{type:'text',text}], isError}`,
 * so the shape lines up without needing an adapter.
 */
export function classify(text: string, isError: boolean | undefined): Classification {
  if (!isError) {
    return { kind: FailureKind.OK, source: FailureKindSource.CLEAN };
  }
  if (!text) {
    return { kind: FailureKind.UNCLASSIFIED, source: FailureKindSource.UNCLASSIFIED };
  }
  if (UNKNOWN_TOOL_PATTERNS.some((pattern) => pattern.test(text))) {
    return { kind: FailureKind.UNKNOWN_TOOL, source: FailureKindSource.SDK_DISPATCH };
  }
  if (INVALID_ARGUMENTS_PATTERN.test(text)) {
    return { kind: FailureKind.INVALID_ARGUMENTS, source: FailureKindSource.SDK_DISPATCH };
  }
  return { kind: FailureKind.TOOL_ERROR, source: FailureKindSource.IS_ERROR_FLAG };
}

/**
 * Extracts the first text block from a CallToolResult-shaped object,
 * tolerating the handful of shapes actually seen: SDK-native results
 * (`{content: [{type:'text', text}]}`), a thrown Error, or something with no
 * usable text at all.
 */
export function firstText(result: unknown): string {
  if (result && typeof result === "object" && "content" in result) {
    const content = (result as { content?: unknown }).content;
    if (Array.isArray(content)) {
      const block = content.find(
        (item): item is { type: "text"; text: string } =>
          !!item && typeof item === "object" && (item as { type?: unknown }).type === "text",
      );
      if (block) return block.text;
    }
  }
  if (result instanceof Error) return result.message;
  return "";
}

/**
 * The whole entry point: classify a CallToolResult (or an exception a tool
 * genuinely threw -- rare, but McpServer's own dispatch code still lets
 * ErrorCode.UrlElicitationRequired through unwrapped).
 */
export function classifyResult(result: unknown, thrown?: unknown): Classification {
  if (thrown !== undefined) {
    return classify(firstText(thrown), true);
  }
  const isError =
    result && typeof result === "object" && "isError" in result
      ? Boolean((result as { isError?: boolean }).isError)
      : false;
  return classify(firstText(result), isError);
}
